### PR TITLE
Create example.py

### PR DESCRIPTION
**Pull request by higoyal01**
*Issue #, if available:* 
https://github.com/aws-samples/serverless-snippets/issues/84

*Description of changes:*
Added example.py for integration-sns-to-lambda as per the https://app.asana.com/0/1205793188023475/1205865797051932

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by boyney123** [comment]
Thanks!

Can you please update the snippet-data.json file within this snippet folder please? Add this file and lang to the array inside there.

**Comment by higoyal01** [comment]
Updated the snippet-data.json file as requested.

**Review by eldritchideen — APPROVED** [review]
Looks good.

**Comment by boyney123** [comment]
Thanks!

**Pull request merged**
