### PR TITLE
Added Ruby example in Lambda-SQS with Batch failures

### PR DESCRIPTION
**Pull request by higoyal01**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by boyney123** [comment]
Thanks @higoyal01 , in the `snippets` array in the snippet-json file can you add your file please?

**Comment by higoyal01** [comment]
Hi @boyney123, I have added my file in snippets array of the snippet-json file. Thanks!

**Comment by dpruessner** [comment]
@higoyal01 I see you added `"Ruby"` into `languages` field; I believe you also need to add an entry in the `$.snippets[0].codeTabs`  for a description of the Ruby example-- something like:

```
        {
          "id": "Ruby",
          "title": "Usage Example with Ruby:",
          "description": "Consuming an SQS event with Lambda using Ruby with batch item handling.",
          "snippets": [
            {
              "snippetPath": "example.rb",
              "language": "ruby"
            }
          ]
        }
```

**Comment by higoyal01** [comment]
Thank you for pointing this out @dpruessner. I have updated the file as per the above comment.

**Review by dpruessner — APPROVED** [review]

**Pull request merged**
